# ./Taskfile.yaml
# See: https://taskfile.dev/api/  

version: "3"  

tasks:  
  default:
    cmds:
      - task: billing  
  billing:
    deps:
      - init_db
    cmds:
      - go run ./cmd/billing --config=./config/dev.yaml

  init_db:
    aliases:
      - db
    cmds:
      - go run ./cmd/migrator --uri=postgres:postgres@localhost:5432/postgres --migrations-path=migrations 
  test_db:
    cmds:
      - go run ./cmd/migrator --uri=postgres:postgres@localhost:5432/tests --migrations-path=migrations 

  test:
    deps:
      - test_db
    cmds:
      - go run ./cmd/billing --config=./config/tests.yaml