# ./Taskfile.yaml
# See: https://taskfile.dev/api/  

version: "3"  

tasks:  
  default:
    cmds:
      - task: billing  
  billing:
    deps:
      - init_db
    cmds:
      - go run ./cmd/billing --config=./config/dev.yaml

  init_db:
    env:
      CONFIG_PATH: ./config/dev.yaml
    aliases:
      - db
    cmds:
      - go run ./cmd/migrator --migrations-path=migrations 
  test_db:
    env:
      CONFIG_PATH: ./config/tests.yaml
    cmds:
      - go run ./cmd/migrator --migrations-path=migrations --clear
      - go run ./cmd/migrator --migrations-path=migrations 

  test:
    deps:
      - test_db
    cmds:
      - go run ./cmd/billing --config=./config/tests.yaml